#!/bin/bash

#pacman -S --needed --noconfirm git mingw-w64-ucrt-x86_64-{toolchain,pkgconf,zstd,lz4,xxhash,openssl,python,cython,python-setuptools,python-wheel,python-pkgconfig,python-packaging,python-msgpack,python-pip}
#pip install pyinstaller

pacman --sync --noconfirm python python-pip base-devel gcc openssl-devel pkgconf openssh ssh-pageant
#pip3 install pipx
#pipx ensurepath
#SETUPTOOLS_USE_DISTUTILS=stdlib pipx install borgbackup --verbose


