name: Windows CI
on: [push, pull_request]

jobs:
  msys2-ucrt64-without-pyinstaller:
    timeout-minutes: 15
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
      - name: Install dependencies
        run: ./scripts/msys2-install-deps
      

      - name: Print Python paths
        run: |
          which python
          which python3
          which pip
          which pip3
      - name: Print Python version
        run: python --version
      # `sys.platform` MUST NOT be "win32" as borg does not support ssh repositories there.
      # On a working MSYS2 setup, it should print "cygwin".
      - name: Print Python platform
        run: python -c 'import sys; print(sys.platform)'

      - name: Install borg
        run: SETUPTOOLS_USE_DISTUTILS=stdlib pip install .

      # Test borg
      - name: Create repository directory
        run: |
          mkdir -p /tmp/backup
          ls -alR /tmp/backup
      - name: borg init
        run: borg init --encryption none --debug /tmp/backup
      - name: borg create
        run: borg create --debug /tmp/backup::test01 /etc
      - name: borg list
        run: borg list --debug /tmp/backup
